[template.environment]
  MORALIS_API_KEY = "MORALIS_API_KEY (Get your KEY https://admin.moralis.io/web3apis)"
  NEXTAUTH_SECRET = "NEXTAUTH_SECRET (Generate it here https://generate-secret.now.sh/64)"
  NEXTAUTH_URL = "NEXTAUTH_URL (Url of your Application)"